DROP TABLE IF EXISTS dm_curso CASCADE;
DROP TABLE IF EXISTS dm_departamento CASCADE;
DROP TABLE IF EXISTS dm_disciplina CASCADE;
DROP TABLE IF EXISTS dm_tempo CASCADE;
DROP TABLE IF EXISTS ft_reprovacao CASCADE;
DROP TABLE IF EXISTS ft_reprovacao_gc CASCADE;